module : cnn.feature_extraction.FeatureExtraction
model : cnn.OneHeadResNet50Model
data_root : dataframes
image_root : images
dataset : cataract1k_feature_extract.Cataract1kFeatureExtract
out_features : 13
input_height : 224
input_width : 224
batch_size : 64
fps_sampling : 1
fps_sampling_test : 1
learning_rate : 0.0005
dataset_mode : img_multilabel
early_stopping_metric : val_acc_phase
pretrained : True
save_top_k : 5
max_epochs : 15 # 30
min_epochs : 6 # 20
num_tasks : 1
num_sanity_val_steps : 4
test_extract : False
#accelerator: ddp_spawn
num_workers : 6
gpus : 0 # all available -1
#resume_from_checkpoint : logs/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model/checkpoints/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model-epoch=10-val_acc_phase=0.83.ckpt

