module : mstcn.tecno.TeCNO
model : mstcn.MultiStageModel
dataset : cataract101.Cataract101
out_features : 10
num_workers : 3
batch_size : 1
features_per_seconds : 1
features_subsampling : 1
log_every_n_steps : 1
mstcn_causal_conv : True
learning_rate : 0.00007
min_epochs : 25
max_epochs : 30
mstcn_layers : 9
mstcn_f_maps : 64
mstcn_f_dim: 2048
mstcn_stages : 2
early_stopping_metric : val_loss
save_top_k : 10
gpus : ['1']
data_root : /Users/haotongwang/Documents/programming/idp/TeCNO/logs/250410-140616_FeatureExtraction_Cataract101FeatureExtract_cnn_OneHeadResNet50Model/cataract_pickle_export/
num_sanity_val_steps: 0
